# Generated by Django 5.0.3 on 2024-03-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rounddata_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebriefForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.CharField(max_length=64)),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('responses', models.CharField(max_length=5120)),
            ],
            options={
                'verbose_name': 'Debrief Form',
                'verbose_name_plural': 'Debrief Responses',
            },
        ),
    ]
