# Generated by Django 5.0.3 on 2024-03-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_debriefform'),
    ]

    operations = [
        migrations.AddField(
            model_name='debriefform',
            name='questions',
            field=models.CharField(default='', max_length=5120),
            preserve_default=False,
        ),
    ]
