# Generated by Django 5.0.3 on 2024-04-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_debriefform_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='debriefform',
            name='prolificParams',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='rounddata',
            name='prolificParams',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
